
CATEGORIES=	russian
MASTER_SITES=	https://ru.wordpress.org/
PKGNAMESUFFIX=	${PHP_PKGNAMESUFFIX}

CONFLICTS_INSTALL=	wordpress de-wordpress fr-wordpress ja-wordpress

WORDPRESS_LANG=	ru_RU

DISTINFO_FILE=	${.CURDIR}/distinfo

MASTERDIR=	${.CURDIR}/../../www/wordpress

.include "${MASTERDIR}/Makefile"
